# Fichier de configuration pour GitHub Pages avec Jekyll

# Le titre de ton site
title: "Mon site hébergé sur GitHub Pages"

# Description de ton site (utilisée pour le SEO)
description: "Description de mon site personnel"

# URL de base du site (c'est l'URL publique où ton site est accessible)
url: "https://enniriss.github.io/Flower/"

# Si ton site est hébergé dans un sous-répertoire, indique ici le nom du dépôt
# Exemple: /ton-repo si ton site est hébergé sur https://ton-nom.github.io/ton-repo/
baseurl: ""

# Auteur du site (ton nom)
author: "SissiK"

# D'autres configurations globales
markdown: kramdown
highlighter: rouge

# Répertoires à exclure lors de la génération du site (facultatif)
exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"



# Inclure un favicon (facultatif)
favicon: "./assets/images/icon.png"
